### ISSUE TITLE
No deployment Record

### ISSUE THREAD

**Issue by Lokeshm24** [f00b4r/strapi-plugin-vercel#5]
Deploy button triggers the deployment on vercel but it always shows "no deployment" in strapi.
How can I get deployment record/status to show inside strapi?

PS - There is no error in api's or build.

**Comment by Zedashe** [comment]
This is because the package is not compatible with all versions of Strapi, if you create a Strapi plugin using the command `yarn strapi generate:plugin vercel` and copy the code from `strapi-plugin-vercel` into this freshly created template which is compatible with your version of Strapi, it should work. That's what I did and it works perfectly.

Don't forget to update the `services/vercel.js` and add the `?teamId=<vercel-team-id>` param to work with **Teams** project and change the API paths from the right ones.

I'll create and maintain an npm package asap.

**Comment by f3l1x** [comment]
Hey @Zedashe. Why would you create a new npm package?

**Comment by Zedashe** [comment]
Hey @f3l1x, sorry mate I thought you weren't active, I'll suggest a PR then 😄.

**Comment by f3l1x** [comment]
Nope. I am alive and active. :D

**Comment by f3l1x** [comment]
Hi @Lokeshm24 and @GeorgS. Version 0.0.7 solved personal vs team deployments and also scoped tokens.
